[package]
name = "tin"
version = "0.1.0"
edition = "2018"

[workspace]
members = [".", "tin_core"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tin_core = { path = "./tin_core" }
